### PR TITLE
fix(static-msg): support binary expressions

### LINKED ISSUE #79: `-static-msg` raise an error on static string concatenation
The following code:

```go
logger.Warn(
    "this is a really long message, that " +
    "requires to split the line",
)
```

Raises the following error in `golangci-lint@v2.0.2` (which uses `simpler.org/sloglint@v0.9.0`):
```
message should be a string literal or a constant (sloglint)
```

The message is constant even though it is built with string concatenation to split long lines.

Related to https://github.com/go-simpler/sloglint/issues/17

### PR DESCRIPTION
**Pull request by tmzane**
Fixes #79

### CODE REVIEW

File: sloglint.go [hunk 1]
```diff
@@ -376,6 +376,8 @@ func isStaticMsg(msg ast.Expr) bool {
 		return msg.Kind == token.STRING
 	case *ast.Ident: // e.g. const msg = "msg"; slog.Info(msg)
 		return msg.Obj != nil && msg.Obj.Kind == ast.Con
+	case *ast.BinaryExpr: // e.g. slog.Info("x" + "y")
```
Comment (ccoVeille) [inline sloglint.go:379]: Don't you need to check the operator?

https://pkg.go.dev/go/ast#BinaryExpr

File: testdata/src/static_msg/static_msg.go [hunk 2]
```diff
@@ -23,13 +23,20 @@ func tests() {
...
 	slog.InfoContext(ctx, fmt.Sprintf("msg"))          // want `message should be a string literal or a constant`
 	slog.Log(ctx, slog.LevelInfo, fmt.Sprintf("msg"))  // want `message should be a string literal or a constant`
 	slog.With("key", "value").Info(fmt.Sprintf("msg")) // want `message should be a string literal or a constant`
 
-	slog.Info(varMsg)                      // want `message should be a string literal or a constant`
-	slog.InfoContext(ctx, varMsg)          // want `message should be a string literal or a constant`
-	slog.Log(ctx, slog.LevelInfo, varMsg)  // want `message should be a string literal or a constant`
-	slog.With("key", "value").Info(varMsg) // want `message should be a string literal or a constant`
+	// binary expressions:
+	slog.Info("msg" + "msg")
```
Comment (ccoVeille) [inline testdata/src/static_msg/static_msg.go:37]: Adding check for consecutive concatenation could help 

```suggestion
	slog.Info("msg" + "msg")
	slog.Info("msg" + "msg" + "msg")
```

You added this

        slog.Info("msg" + constMsg + varMsg + fmt.Sprintf("msg")) // want `message should be a string literal or a constant`

But as an invalid one

Comment (mattdowdell) [reply testdata/src/static_msg/static_msg.go:37]: Agreed, having a check to exercise an extra level of recursion would be helpful.

**Review by mattdowdell — APPROVED** [review]
LGTM, although the points raised by @ccoVeille are worth thinking about a little before merging.

File: sloglint.go (hunk 1 above)
Comment (tmzane) [reply sloglint.go:382]: Yep, only `+` can be applied to strings. Added an assertion just in case

File: testdata/src/static_msg/static_msg.go [hunk 3]
```diff
@@ -23,13 +23,21 @@ func tests() {
...
+	slog.Info("msg" + "msg" + "msg")
+	slog.Info("msg" + constMsg)
+	slog.Info("msg" + varMsg)                                 // want `message should be a string literal or a constant`
```
Comment (ccoVeille) [inline testdata/src/static_msg/static_msg.go:40]: I'm unsure about this one. A variable value can change

Imagine a code like this

```go
var status = "OK"
slog.Info("status:" + status)

// something happen and now
var status = "Broken"
slog.Info("status:" + status)
```

But maybe I didn't understand what the linter reports

File: testdata/src/static_msg/static_msg.go [hunk 4]
```diff
@@ -23,13 +23,21 @@ func tests() {
...
 	slog.InfoContext(ctx, fmt.Sprintf("msg"))          // want `message should be a string literal or a constant`
 	slog.Log(ctx, slog.LevelInfo, fmt.Sprintf("msg"))  // want `message should be a string literal or a constant`
 	slog.With("key", "value").Info(fmt.Sprintf("msg")) // want `message should be a string literal or a constant`
 
-	slog.Info(varMsg)                      // want `message should be a string literal or a constant`
-	slog.InfoContext(ctx, varMsg)          // want `message should be a string literal or a constant`
-	slog.Log(ctx, slog.LevelInfo, varMsg)  // want `message should be a string literal or a constant`
-	slog.With("key", "value").Info(varMsg) // want `message should be a string literal or a constant`
+	// binary expressions:
+	slog.Info("msg" + "msg")
```
Comment (ccoVeille) [inline testdata/src/static_msg/static_msg.go:37]: What about adding these to the tests

```suggestion
	slog.Info("msg" + "msg")
	slog.Info(`msg`)
	slog.Info("msg" + `msg`)
```

File: testdata/src/static_msg/static_msg.go (hunk 3 above)
Comment (tmzane) [reply testdata/src/static_msg/static_msg.go:40]: That's why we report this case, note the comment on the right.

File: testdata/src/static_msg/static_msg.go (hunk 4 above)
Comment (tmzane) [reply testdata/src/static_msg/static_msg.go:37]: `strings.Unquote` has its own tests, don't worry about it :)

File: testdata/src/static_msg/static_msg.go (hunk 3 above)
Comment (ccoVeille) [reply testdata/src/static_msg/static_msg.go:40]: Oh that's the message, it makes sense to me now.

**Review by ccoVeille — APPROVED** [review]
